version: "3.5"

services:

  redis:
    image: redis:latest

  backend:
    image: jclc/example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      
  frontend:
    image: jclc/example-frontend
    ports:
      - 5000:5000
