version: "3.5"

services:

  redis:
    image: redis:latest
    container_name: redis

  backend:
    image: jclc/example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: FGv7R053hVbAB3YnwVn5b0mCD824stLkEwJ1DTVI3J6hPdoiZvyPMPi5IHSP32DS
    depends_on:
      - database
      
  frontend:
    image: jclc/example-frontend
    container_name: frontend
    ports:
      - 5000:5000

  database:
    image: postgres:13.2-alpine
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: FGv7R053hVbAB3YnwVn5b0mCD824stLkEwJ1DTVI3J6hPdoiZvyPMPi5IHSP32DS
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume: