version: "3.5"

services:

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - internal-network

  backend:
    image: jclc/example-backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: FGv7R053hVbAB3YnwVn5b0mCD824stLkEwJ1DTVI3J6hPdoiZvyPMPi5IHSP32DS
    depends_on:
      - database
    networks:
      - internal-network
      
  frontend:
    image: jclc/example-frontend
    container_name: frontend
    ports:
      - 5000:5000
    networks:
      - internal-network

  database:
    image: postgres:13.2-alpine
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: FGv7R053hVbAB3YnwVn5b0mCD824stLkEwJ1DTVI3J6hPdoiZvyPMPi5IHSP32DS
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - internal-network

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal-network
    depends_on:
      - backend
      - frontend

volumes:
  db_volume:
  
networks:
  internal-network:
    name: internal-network