version: "3.5"

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes:
      - ${PWD}/text.log:/usr/src/app/text.log
    container_name: web-service
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    command:
      - server